import type { PnLReport, BalanceSheetReport, CashFlowReport, LineItem } from "@/types/reports";

type SheetRow = (string | number)[];

/* ── Download helpers ── */

async function downloadFile(content: string | ArrayBuffer, filename: string, mimeType: string) {
  const { saveAs } = await import("file-saver");
  const blob = new Blob([content], { type: mimeType });
  saveAs(blob, filename);
}

async function getXLSX() {
  const XLSX = await import("xlsx");
  return XLSX;
}

/* ── P&L ── */

function buildPnLRows(report: PnLReport): SheetRow[] {
  const rows: SheetRow[] = [
    ["Profit & Loss Statement"],
    ["Period:", report.period_label],
    [],
    ["INCOME", ""],
    ...report.income.items.map((i): SheetRow => [i.label, i.amount]),
    [report.income.totalLabel, report.income.total],
    [],
    ["EXPENSES", ""],
    ...report.expenses.items.map((i): SheetRow => [i.label, i.amount]),
    [report.expenses.totalLabel, report.expenses.total],
    [],
    ["NET PROFIT / (LOSS)", report.net_profit],
    ["Net Margin", `${report.net_margin_percent}%`],
    [],
    ...(report.reviewed_by ? [["Reviewed by:", report.reviewed_by]] : []),
    ["Generated by AccuBridge", new Date().toLocaleDateString("en-GB")],
  ];
  return rows;
}

export async function exportPnLToCSV(report: PnLReport, filename: string): Promise<void> {
  const rows = buildPnLRows(report);
  const csv  = rows.map((r) => r.map((c) => `"${c}"`).join(",")).join("\n");
  await downloadFile(csv, filename, "text/csv;charset=utf-8;");
}

export async function exportPnLToXLSX(report: PnLReport, filename: string): Promise<void> {
  const XLSX = await getXLSX();
  const ws   = XLSX.utils.aoa_to_sheet(buildPnLRows(report));
  const wb   = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Profit & Loss");
  const buf  = XLSX.write(wb, { bookType: "xlsx", type: "array" }) as ArrayBuffer;
  await downloadFile(buf, filename, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
}

/* ── Balance Sheet ── */

function buildBalanceRows(report: BalanceSheetReport): SheetRow[] {
  const addGroup = (items: LineItem[], totalLabel: string, total: number): SheetRow[] => [
    ...items.map((i): SheetRow => [i.label, i.amount]),
    [totalLabel, total],
    [],
  ];

  return [
    ["Balance Sheet"],
    ["As of:", report.as_of_date],
    [],
    ["ASSETS"],
    [report.assets.current.title],
    ...addGroup(report.assets.current.items, report.assets.current.totalLabel, report.assets.current.total),
    [report.assets.non_current.title],
    ...addGroup(report.assets.non_current.items, report.assets.non_current.totalLabel, report.assets.non_current.total),
    ["TOTAL ASSETS", report.assets.total_assets],
    [],
    ["LIABILITIES"],
    [report.liabilities.current.title],
    ...addGroup(report.liabilities.current.items, report.liabilities.current.totalLabel, report.liabilities.current.total),
    [report.liabilities.non_current.title],
    ...addGroup(report.liabilities.non_current.items, report.liabilities.non_current.totalLabel, report.liabilities.non_current.total),
    ["TOTAL LIABILITIES", report.liabilities.total_liabilities],
    [],
    ["EQUITY"],
    ...report.equity.items.map((i): SheetRow => [i.label, i.amount]),
    ["TOTAL EQUITY", report.equity.total_equity],
    [],
    ["TOTAL LIABILITIES & EQUITY", report.total_liabilities_and_equity],
    ["Balance Check:", report.is_balanced ? "✓ Balanced" : "✗ Imbalanced"],
    [],
    ...(report.reviewed_by ? [["Reviewed by:", report.reviewed_by]] : []),
    ["Generated by AccuBridge", new Date().toLocaleDateString("en-GB")],
  ];
}

export async function exportBalanceSheetToCSV(report: BalanceSheetReport, filename: string): Promise<void> {
  const rows = buildBalanceRows(report);
  const csv  = rows.map((r) => r.map((c) => `"${c}"`).join(",")).join("\n");
  await downloadFile(csv, filename, "text/csv;charset=utf-8;");
}

export async function exportBalanceSheetToXLSX(report: BalanceSheetReport, filename: string): Promise<void> {
  const XLSX = await getXLSX();
  const ws   = XLSX.utils.aoa_to_sheet(buildBalanceRows(report));
  const wb   = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Balance Sheet");
  const buf  = XLSX.write(wb, { bookType: "xlsx", type: "array" }) as ArrayBuffer;
  await downloadFile(buf, filename, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
}

/* ── Cash Flow ── */

function buildCashFlowRows(report: CashFlowReport): SheetRow[] {
  const addSection = (title: string, items: LineItem[], totalLabel: string, total: number): SheetRow[] => [
    [title],
    ...items.map((i): SheetRow => [i.label, i.amount]),
    [totalLabel, total],
    [],
  ];

  return [
    ["Cash Flow Statement"],
    ["Period:", report.period_label],
    [],
    ["Opening Cash Balance", report.opening_balance],
    [],
    ...addSection("OPERATING ACTIVITIES", report.operating.items, report.operating.totalLabel, report.operating.total),
    ...addSection("INVESTING ACTIVITIES", report.investing.items, report.investing.totalLabel, report.investing.total),
    ...addSection("FINANCING ACTIVITIES", report.financing.items, report.financing.totalLabel, report.financing.total),
    ["NET CHANGE IN CASH", report.net_change],
    ["CLOSING CASH BALANCE", report.closing_balance],
    [],
    ...(report.reviewed_by ? [["Reviewed by:", report.reviewed_by]] : []),
    ["Generated by AccuBridge", new Date().toLocaleDateString("en-GB")],
  ];
}

export async function exportCashFlowToCSV(report: CashFlowReport, filename: string): Promise<void> {
  const rows = buildCashFlowRows(report);
  const csv  = rows.map((r) => r.map((c) => `"${c}"`).join(",")).join("\n");
  await downloadFile(csv, filename, "text/csv;charset=utf-8;");
}

export async function exportCashFlowToXLSX(report: CashFlowReport, filename: string): Promise<void> {
  const XLSX = await getXLSX();
  const ws   = XLSX.utils.aoa_to_sheet(buildCashFlowRows(report));
  const wb   = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Cash Flow");
  const buf  = XLSX.write(wb, { bookType: "xlsx", type: "array" }) as ArrayBuffer;
  await downloadFile(buf, filename, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");
}
