import type { PnLReport, BalanceSheetReport, CashFlowReport, LineItem } from "@/types/reports";

const PRIMARY  = "#0A2463";
const GOLD     = "#D4AF37";
const GREEN    = "#06D6A0";
const RED      = "#ef4444";
const MUTED    = "#6B7280";

/* ── Helpers ── */

function gbp(v: number): string {
  const abs = Math.abs(v).toLocaleString("en-GB", { minimumFractionDigits: 2 });
  return v < 0 ? `(£${abs})` : `£${abs}`;
}

async function getJsPDF() {
  const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
    import("jspdf"),
    import("jspdf-autotable"),
  ]);
  return { jsPDF, autoTable };
}

function addBrandedHeader(doc: InstanceType<typeof import("jspdf").default>, title: string, subtitle: string) {
  // Header background
  doc.setFillColor(10, 36, 99);
  doc.rect(0, 0, 210, 28, "F");

  // Gold accent bar
  doc.setFillColor(212, 175, 55);
  doc.rect(0, 28, 210, 1.5, "F");

  // Logo text
  doc.setTextColor(212, 175, 55);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("AccuBridge", 14, 12);

  // Tagline
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.text("Financial Management Platform", 14, 18);

  // Report title (right aligned)
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(255, 255, 255);
  doc.text(title, 196, 12, { align: "right" });

  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(212, 175, 55);
  doc.text(subtitle, 196, 18, { align: "right" });
}

function addFooter(doc: InstanceType<typeof import("jspdf").default>, reviewedBy?: string) {
  const pageH = doc.internal.pageSize.getHeight();
  doc.setFillColor(10, 36, 99);
  doc.rect(0, pageH - 12, 210, 12, "F");
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(255, 255, 255);
  if (reviewedBy) {
    doc.text(`Reviewed by: ${reviewedBy}`, 14, pageH - 5);
  }
  doc.text("Generated by AccuBridge · Confidential", 196, pageH - 5, { align: "right" });
}

/* ── P&L PDF ── */

export async function exportPnLToPDF(report: PnLReport, filename: string): Promise<void> {
  const { jsPDF, autoTable } = await getJsPDF();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  addBrandedHeader(doc, "Profit & Loss", report.period_label);

  const rows: [string, string][] = [];

  rows.push(["INCOME", ""] as unknown as [string, string]);
  report.income.items.forEach((i) => rows.push([`  ${i.label}`, gbp(i.amount)]));
  rows.push([report.income.totalLabel, gbp(report.income.total)]);
  rows.push(["", ""]);

  rows.push(["EXPENSES", ""] as unknown as [string, string]);
  report.expenses.items.forEach((i) => rows.push([`  ${i.label}`, gbp(i.amount)]));
  rows.push([report.expenses.totalLabel, gbp(report.expenses.total)]);
  rows.push(["", ""]);

  rows.push(["NET PROFIT / (LOSS)", gbp(report.net_profit)]);

  autoTable(doc, {
    startY: 36,
    head: [["Description", "Amount (£)"]],
    body: rows,
    theme: "plain",
    styles: { font: "helvetica", fontSize: 9, cellPadding: { top: 2.5, bottom: 2.5, left: 4, right: 4 }, textColor: [30, 30, 40] },
    headStyles: { fillColor: [10, 36, 99], textColor: [255, 255, 255], fontStyle: "bold", fontSize: 9 },
    columnStyles: { 1: { halign: "right" } },
    didParseCell: (data) => {
      const label = String(data.cell.raw ?? "");
      if (data.column.index === 0 && /^(INCOME|EXPENSES)$/.test(label.trim())) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [10, 36, 99];
        data.cell.styles.textColor = [62, 146, 204];
        data.cell.styles.fontSize  = 8;
      }
      if (label === report.income.totalLabel || label === report.expenses.totalLabel) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [240, 240, 245];
      }
      if (label === "NET PROFIT / (LOSS)" || (data.column.index === 1 && Array.isArray(data.row.raw) && (data.row.raw as string[])[0] === "NET PROFIT / (LOSS)")) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [234, 224, 187];
        data.cell.styles.textColor = report.net_profit >= 0 ? [6, 214, 160] : [239, 68, 68];
        data.cell.styles.fontSize  = 10;
      }
    },
  });

  addFooter(doc, report.reviewed_by);
  doc.save(filename);
}

/* ── Balance Sheet PDF ── */

export async function exportBalanceSheetToPDF(report: BalanceSheetReport, filename: string): Promise<void> {
  const { jsPDF, autoTable } = await getJsPDF();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  addBrandedHeader(doc, "Balance Sheet", `As of ${report.as_of_date}`);

  type Row = [string, string];
  const rows: Row[] = [];

  const addGroup = (items: LineItem[], totalLabel: string, total: number) => {
    items.forEach((i) => rows.push([`  ${i.label}`, gbp(i.amount)]));
    rows.push([totalLabel, gbp(total)]);
    rows.push(["", ""]);
  };

  rows.push(["ASSETS", ""]);
  rows.push([report.assets.current.title, ""]);
  addGroup(report.assets.current.items, report.assets.current.totalLabel, report.assets.current.total);
  rows.push([report.assets.non_current.title, ""]);
  addGroup(report.assets.non_current.items, report.assets.non_current.totalLabel, report.assets.non_current.total);
  rows.push(["TOTAL ASSETS", gbp(report.assets.total_assets)]);
  rows.push(["", ""]);

  rows.push(["LIABILITIES", ""]);
  rows.push([report.liabilities.current.title, ""]);
  addGroup(report.liabilities.current.items, report.liabilities.current.totalLabel, report.liabilities.current.total);
  rows.push([report.liabilities.non_current.title, ""]);
  addGroup(report.liabilities.non_current.items, report.liabilities.non_current.totalLabel, report.liabilities.non_current.total);
  rows.push(["TOTAL LIABILITIES", gbp(report.liabilities.total_liabilities)]);
  rows.push(["", ""]);

  rows.push(["EQUITY", ""]);
  report.equity.items.forEach((i) => rows.push([`  ${i.label}`, gbp(i.amount)]));
  rows.push(["TOTAL EQUITY", gbp(report.equity.total_equity)]);
  rows.push(["", ""]);

  rows.push(["TOTAL LIABILITIES & EQUITY", gbp(report.total_liabilities_and_equity)]);

  autoTable(doc, {
    startY: 36,
    head: [["Description", "Amount (£)"]],
    body: rows,
    theme: "plain",
    styles: { font: "helvetica", fontSize: 9, cellPadding: { top: 2.5, bottom: 2.5, left: 4, right: 4 }, textColor: [30, 30, 40] },
    headStyles: { fillColor: [10, 36, 99], textColor: [255, 255, 255], fontStyle: "bold" },
    columnStyles: { 1: { halign: "right" } },
    didParseCell: (data) => {
      const label = String(data.cell.raw ?? "").trim();
      if (/^(ASSETS|LIABILITIES|EQUITY)$/.test(label)) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [10, 36, 99];
        data.cell.styles.textColor = [62, 146, 204];
      }
      if (/^(TOTAL ASSETS|TOTAL LIABILITIES|TOTAL EQUITY)$/.test(label) ||
          /^Total (Current|Non-Current)/.test(label)) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [240, 240, 245];
      }
      if (label === "TOTAL LIABILITIES & EQUITY") {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fontSize  = 10;
        data.cell.styles.textColor = [212, 175, 55];
      }
    },
  });

  addFooter(doc, report.reviewed_by);
  doc.save(filename);
}

/* ── Cash Flow PDF ── */

export async function exportCashFlowToPDF(report: CashFlowReport, filename: string): Promise<void> {
  const { jsPDF, autoTable } = await getJsPDF();
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  addBrandedHeader(doc, "Cash Flow Statement", report.period_label);

  type Row = [string, string];
  const rows: Row[] = [];

  rows.push(["Opening Cash Balance", gbp(report.opening_balance)]);
  rows.push(["", ""]);

  const addSection = (title: string, items: LineItem[], totalLabel: string, total: number) => {
    rows.push([title, ""]);
    items.forEach((i) => rows.push([`  ${i.label}`, gbp(i.amount)]));
    rows.push([totalLabel, gbp(total)]);
    rows.push(["", ""]);
  };

  addSection("OPERATING ACTIVITIES", report.operating.items, report.operating.totalLabel, report.operating.total);
  addSection("INVESTING ACTIVITIES", report.investing.items, report.investing.totalLabel, report.investing.total);
  addSection("FINANCING ACTIVITIES", report.financing.items, report.financing.totalLabel, report.financing.total);

  rows.push(["NET CHANGE IN CASH", gbp(report.net_change)]);
  rows.push(["CLOSING CASH BALANCE", gbp(report.closing_balance)]);

  autoTable(doc, {
    startY: 36,
    head: [["Description", "Amount (£)"]],
    body: rows,
    theme: "plain",
    styles: { font: "helvetica", fontSize: 9, cellPadding: { top: 2.5, bottom: 2.5, left: 4, right: 4 }, textColor: [30, 30, 40] },
    headStyles: { fillColor: [10, 36, 99], textColor: [255, 255, 255], fontStyle: "bold" },
    columnStyles: { 1: { halign: "right" } },
    didParseCell: (data) => {
      const label = String(data.cell.raw ?? "").trim();
      if (/^(OPERATING|INVESTING|FINANCING) ACTIVITIES/.test(label)) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [10, 36, 99];
        data.cell.styles.textColor = [62, 146, 204];
      }
      if (/^Net Cash from/.test(label)) {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fillColor = [240, 240, 245];
      }
      if (label === "CLOSING CASH BALANCE" || label === "NET CHANGE IN CASH") {
        data.cell.styles.fontStyle = "bold";
        data.cell.styles.fontSize  = 10;
        data.cell.styles.textColor = [212, 175, 55];
      }
    },
  });

  addFooter(doc, report.reviewed_by);
  doc.save(filename);
}
